import './screenAnnotations/screenAnnotationsButton.controller';
import './screenAnnotations/screenAnnotationInfoPopup.controller';
import './screenAnnotations/screenAnnotations.service';
import './stepNotFound/stepNotFound.component';
import './fallback/fallback.component';
import './navigation/stepNavigation.component';
import './comparison/comparisonToolbar.component';
import './comparison/comparisonView.controller';
import './oldstep.controller';
