@startuml

object "<u>scenario: Scenario" as scenario {
    name = "Search Book by Author"
}

object "<u>scenarioDetails: Details" as scenarioDetails
note top
 Details are key-value-maps,
 where values can be of type ObjectDescription
 to define further objects
end note

scenario -> scenarioDetails : details

object "<u>service1: ObjectDescription" as service1 {
  type = "service"
  name = "Search"
}

scenarioDetails --> service1 : service1


object "<u>service2: ObjectDescription" as service2 {
  type = "service"
  name = "Rating"
}

scenarioDetails --> service2 : service2


object "<u>service1Details: Details" as service1Details {
    method = "GET"
    url = "http://mybookstore.com/api/search"
    query-param = "?q=Kafka"
    response = "<books><book>Der Prozess</book></books>"
}

note bottom
    Simple Details example
    with only String as values.
end note

service1 --> service1Details : details

object "<u>service2Details: Details" as service2Details {
    method: "GET"
    url: "http://mybookstore.com/api/rating"
    query-param: "?author=kafka&book=der+prozess"
    response: "5"
  }

service2 --> service2Details : details

@enduml
